### PR TITLE
Fix incorrect wanted value in Radarr widget

### LINKED ISSUE #397: Bug: Radarr widget incorrectly interprets `isAvailable`
For radarr, @benphelps, I think you are misinterpreting the value "isAvailable: false"... It mean it's not in local Radarr library **and not yet available**, it simply mean it is not available at all, it's a futur movie not available period. So counting "isAvailable: false" will result in a partial Wanted/Missing totalRecords...

You should count "sizeOnDisk": 0 to determined Wanted/Missing movies in a local Radarr Library.

_Originally posted by @Magelo in https://github.com/benphelps/homepage/issues/43#issuecomment-1279971986_

### PR DESCRIPTION
**Pull request by JazzFisch**
fixes #397

### CODE REVIEW

**Comment by shamoon** [comment]
Not to complicate things here, but why not `monitored` instead of `isAvailable`? 😬

**Comment by shamoon** [comment]
Ah, see https://github.com/Radarr/Radarr/blob/573405bae7992759f8fb8c1ff87ec6476fb8bb85/frontend/src/Store/Actions/movieActions.js#L69

`monitored && hasFile && isAvailable` =)

File: src/widgets/radarr/widget.js [hunk 1]
```diff
@@ -1,6 +1,18 @@
...
+  // E.g. it's available to stream or on DVD, etc
+  if (item.isAvailable === false) {
+    return false;
+  }
+
+  // sizeOnDisk is how much of that digital image you currently have
+  // movieFile.size is how large the requested digital image is
+  return item.sizeOnDisk === item.movieFile?.size;
+}
+
```
Comment (shamoon) [inline src/widgets/radarr/widget.js:15]:
```suggestion
```

File: src/widgets/radarr/widget.js [hunk 2]
```diff
@@ -9,8 +21,8 @@ const widget = {
     movie: {
       endpoint: "movie",
       map: (data) => ({
-        wanted: jsonArrayFilter(data, (item) => item.isAvailable === false).length,
-        have: jsonArrayFilter(data, (item) => item.isAvailable === true).length,
+        wanted: jsonArrayFilter(data, (item) => !isAvailable(item)).length,
+        have: jsonArrayFilter(data, (item) => isAvailable(item)).length,
```
Comment (shamoon) [inline src/widgets/radarr/widget.js:25]:
```suggestion
        wanted: jsonArrayFilter(data, (item) => item.monitored && !item.hasFile && item.isAvailable).length,
        have: jsonArrayFilter(data, (item) => item.monitored && item.hasFile && item.isAvailable).length,
```

**Review by shamoon — COMMENTED** [review]
I think?

**Comment by shamoon** [comment]
Also, semantically perhaps `moviesData` should be `wanted` and `all`, not `have` =)

**Review by shamoon — APPROVED** [review]
